services:
  sbs-driver-ui:
    image: sbs-driver-ui:1.0.0
    build:
      context: ./sbs-driver/ui
      args:
        - ENVIRONMENT=production
    networks:
      sbs-network:
        aliases:
          - sbs-driver-ui
    depends_on:
      - sbs-driver-api
      - sbs-metrics-ui
      - sbs-metrics-api
      - sbs-project-management-ui
      - sbs-project-management-api
  sbs-driver-api:
    image: sbs-driver-api:1.0.0
    build:
      context: ./sbs-driver/api
      target: prod
    networks:
      sbs-network:
        aliases:
          - sbs-driver-api
  sbs-metrics-ui:
    image: sbs-metrics-ui:1.0.0
    build:
      context: ./sbs-metrics/ui
      args:
        - ENVIRONMENT=production
    networks:
      sbs-network:
        aliases:
          - sbs-metrics-ui
    depends_on:
      - sbs-metrics-api
  sbs-metrics-api:
    image: sbs-metrics-api:1.0.0
    build:
      context: ./sbs-metrics/api
      target: prod
    networks:
      sbs-network:
        aliases:
          - sbs-metrics-api-service
  sbs-project-management-ui:
    image: sbs-project-management-ui:1.0.0
    build:
      context: ./sbs-project-management/ui
      args:
        - ENVIRONMENT=production
    ports:
      - 80:80
    networks:
      sbs-network:
        aliases:
          - sbs-project-management-ui
    depends_on:
      - sbs-project-management-api
  sbs-project-management-api:
    image: sbs-project-management-api:1.0.0
    build:
      context: ./sbs-project-management/api
      target: prod
    networks:
      sbs-network:
        aliases:
          - sbs-project-management-api
networks:
  sbs-network:
