services:
  ui:
    image: sbs-metrics-ui:latest
    build:
      context: ./ui
      target: dev
      args:
        - ENVIRONMENT=development
    volumes:
      - $PWD/ui/src:/app/src
      - /app/node_modules
    ports:
      - "4200:4200"
    depends_on:
      - api
  api:
    image: sbs-metrics-api:latest
    build:
      context: ./api
      target: dev
    ports:
      - "8080:8080"
      - "5005:5005"
